name: Create GitHub Release on PyPI Upload

on:
  release:
    types: [published]  # Triggers on a new GitHub release

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match your project’s Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/* -u __token__ -p "$PYPI_API_TOKEN"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          tag_name: v${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          body: "Automatically released from PyPI."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
